postgresql://postgres.yxpodbgkxsmyuxqjwjno:[YOUR-PASSWORD]@aws-1-eu-west-1.pooler.supabase.com:5432/postgres


https://yxpodbgkxsmyuxqjwjno.supabase.co

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4cG9kYmdreHNteXV4cWp3am5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2ODgzMDksImV4cCI6MjA4OTI2NDMwOX0.PQZcT6DsnKxfchQnM3WbsC-_49Dtjy8vA-8-kCpm23M


sb_publishable_xnBcBBY6GUZYkhZBO7PgAA__H_4pDzp